/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author cpawl
 */
public class LandlordFrame extends javax.swing.JPanel {

    /**
     * Creates new form LandlordPanel
     */
    public LandlordFrame(Landlord person) {
        initComponents();
        currentLogin = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        bedroomLabel = new javax.swing.JLabel();
        bedroomBox = new javax.swing.JComboBox<>();
        bathroomLabel = new javax.swing.JLabel();
        bathroomBox = new javax.swing.JComboBox<>();
        apartmentLabel = new javax.swing.JLabel();
        apartmentBox = new javax.swing.JComboBox<>();
        quadrantLabel = new javax.swing.JLabel();
        quadrantBox = new javax.swing.JComboBox<>();
        furnishedBox = new javax.swing.JCheckBox();
        registerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertiesBox = new javax.swing.JComboBox<>();
        feeButton = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();

        bedroomLabel.setText("Number of bedrooms");

        bedroomBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        bathroomLabel.setText("Number of bathrooms");

        bathroomBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        apartmentLabel.setText("Type of apartment");

        apartmentBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartment", "Attached house", "Detached house", "Townhouse" }));

        quadrantLabel.setText("City quadrant");

        quadrantBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NW", "NE", "SW", "SE" }));

        furnishedBox.setText("Pre-furnished");
        furnishedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                furnishedBoxActionPerformed(evt);
            }
        });

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        propertiesLabel.setText("Apartment list");

        propertiesBox.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(propertiesBox);

        ArrayList<Property> properties = currentLogin.getProperty();
        for (int i = 0; i < properties.size(); i++) {
            propertiesBox.add(properties.get(i).getPropertyAddress());
        }

        jScrollPane1.setViewportView(propertiesBox);

        feeButton.setText("Pay fee");
        feeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeButtonActionPerformed(evt);
            }
        });

        registerLabel.setText("Register new property");

        addressLabel.setText("Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(addressBox, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bedroomLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bedroomBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bathroomLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(bathroomBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(apartmentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(apartmentBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(quadrantLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(quadrantBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(registerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(registerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(furnishedBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(propertiesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(feeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(registerLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bedroomLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bedroomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bathroomLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bathroomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(apartmentLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(apartmentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(quadrantLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(quadrantBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(propertiesLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(feeButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(furnishedBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerButton)
                                .addGap(0, 0, 0))
        );
    }// </editor-fold>

    private void furnishedBoxActionPerformed(java.awt.event.ActionEvent evt) {
        checkbox = !checkbox;
    }

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String type = apartmentBox.getItemAt(apartmentBox.getSelectedIndex());
        String location = addressBox.getText();
        int numBed = bedroomBox.getSelectedIndex() + 1;
        int numBath = bathroomBox.getSelectedIndex() + 1;
        String quadrant = quadrantBox.getItemAt(quadrantBox.getSelectedIndex());
        Property toRegister = new Property(type, numBed, numBath, quadrant, checkbox, location);
        currentLogin.registerProperty(toRegister);
    }

    private void feeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        currentLogin.processPayment(propertiesList.getSelectedIndex());
    }

    // Variables declaration - do not modify
    private javax.swing.JFormattedTextField addressBox;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JComboBox<String> apartmentBox;
    private javax.swing.JLabel apartmentLabel;
    private javax.swing.JComboBox<String> bathroomBox;
    private javax.swing.JLabel bathroomLabel;
    private javax.swing.JComboBox<String> bedroomBox;
    private javax.swing.JLabel bedroomLabel;
    private javax.swing.JButton feeButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JCheckBox furnishedBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> propertiesBox;
    private javax.swing.JLabel propertiesLabel;
    private javax.swing.JComboBox<String> quadrantBox;
    private javax.swing.JLabel quadrantLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabel;

    Landlord currentLogin;
    private boolean checkbox = false;
    // End of variables declaration
}
